### ISSUE TITLE
DresserMod/README.md  not correct link INSTRUCTION.md

### ISSUE THREAD

**Issue by ctdf** [Gorzon38/Mods-Broforce#1]
https://github.com/Gorzon38/Mods-Broforce/blob/main/DresserMod/README.md 
[Instructions](https://github.com/Gorzon38/Mods-Broforce/blob/main/DresserMod/INSTRUCTION.md)  the reference to Instructions points to Instruction without the letter s, but correctly to Instructions. 

current not correct - https://github.com/Gorzon38/Mods-Broforce/blob/main/DresserMod/INSTRUCTION.md
correct https://github.com/Gorzon38/Mods-Broforce/blob/main/DresserMod/INSTRUCTIONS.md

**Comment by Gorzontrok** [comment]
Fixed
